<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ResearchMonitor.Core\ResearchMonitor.Core.csproj" />
    <ProjectReference Include="..\ResearchMonitor.Data\ResearchMonitor.Data.csproj" />
    <ProjectReference Include="..\ResearchMonitor.Collectors\ResearchMonitor.Collectors.csproj" />
    <ProjectReference Include="..\ResearchMonitor.LmStudio\ResearchMonitor.LmStudio.csproj" />
    <ProjectReference Include="..\ResearchMonitor.OpenAI\ResearchMonitor.OpenAI.csproj" />
    <ProjectReference Include="..\ResearchMonitor.Resources\ResearchMonitor.Resources.csproj" />
    <ProjectReference Include="..\ResearchMonitor.Reporting\ResearchMonitor.Reporting.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
